apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  labels:
    app: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: flask
        image: adi0509/flask-test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000