name: k8s-deployment

on:
  workflow_run:
    workflows: ["upload-docker-image"]
    types: 
      - completed

jobs:
  deploy:
    name: Deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ vars.KUBERNETES_URL }}
          k8s-secret: ${{ vars.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml
          images: |
            adi0509/flask-test:latest
      -
        name: redeploy deployment
        run: |
          echo "redeploying flask deployment"
          kubectl rollout restart deployment my-flask-app